### ISSUE TITLE
[mc1.10.2] LittleMaids not spawning with SpongeForge installed.

### ISSUE THREAD

**Issue by tetsune** [Verclene/LittleMaidReengaged#125]
I already created [a report ](https://github.com/SpongePowered/SpongeForge/issues/1874)with SpongeForge, but I wanted to mention it here as well in case this was something fixable on your end?

I cannot spawn a Maid with an egg, command, and they do not spawn naturally with SpongeForge installed.

**Forge Log:**
https://gist.github.com/tetsune/d3ba483e9c32fb7d48ecf179a6c303ab

Spams this whenever maid spawn is attempted naturally or artificially:
https://gist.github.com/phit/b4abac66a766fea82a58c6a04d199c27

**Comment by Verclene** [comment]
It seems that SpongeForge sends inventories to FakePlayer(usually it should not be done because it has no actual client), which Forge does not.
Perhaps SpongeForge bypasses it with FakePlayerFactory-made entities, but the Factory cannot be used to MaidAvatar because of many problems. So currently I can nothing.
Being not able to get SpongeForge-injected sources, so I cannot trace the log either.

**Comment by ryantheleach** [comment]
According to : https://github.com/SpongePowered/Mixin/wiki/Mixin-Java-System-Properties

Setting : `mixin.debug.export` to true will get you the classes mixed into dumped to the file system.

If fern flower is found in the classpath it will also dump sources, otherwise it can be decompiled.

Additionally if you use IntelliJ, using MCDev (nightly releases) can give you additional debugging capabilities with mods that use mixins, like stepping into the mixin classes and setting breakpoints inside them.

**Comment by ryantheleach** [comment]
Forgive me because I don't know much about FakePlayer, but looking at the other methods it stubs, shouldn't it be overriding any methods that send stuff to the network?

e.g. Sponge calls sendContainerToPlayer on EntityPlayerMP's , which calls sendAllContents, which calls this.connection.sendPacket(blah)

So would it be fair to say that Forge's FakePlayer should override sendAllContents and stub the method?

**Comment by Verclene** [comment]
Well, I found that SpongeForge references sendContainerToPlayer(), which uses inventoryContainer, from stopActiveHand().
A maid has EntityLittleMaidAvatarMP(which extends FakePlayer, is used when a maid uses items or etc., and caused this issue) but it does not exist on the world, so it is not referenced directly from the world. Sending its container is almost unnecessary. 
The inventoryContainer has been null on Avatar, which caused this issue.

But just to silence sendContainerToPlayer() might not eliminate all issues related with this. Field inventoryContainer may be used on other places.
This is a trivial question, but is there any necessary to detect FakePlayer's stopping hand BY SENDING CONTAINER?

**Comment by ryantheleach** [comment]
This would be better brought up on the issue on SpongeForge IMO.

I'm only a member of the project in an issue maintenance / support role, and feel it would need the input of some of the developers.

My gut feeling is no, but at the same time the whole FakePlayer thing smells like a hack anyway, with no one having clear lines on how much of EntityPlayerMP any FakePlayer implementation is likely to follow...

But I'm an utter noob when it comes to forge modding, so my opinion isn't very well educated, thus my suggestion to communicate via the issue on SpongeForge

**Comment by Verclene** [comment]
~~Try this release: 8.1.4.131~~
Because Sponge's buildscript is redundant, I have no time to test on SpongeForge.

**Comment by tetsune** [comment]
Just attempted to launch a server with LMMRE, EBLib, and SpongeForge and this came up:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LMRECoremod ([1.9.4-1.10.x]LittleMaidReengaged-8.1.4.131.jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 11/27/17 5:34 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from LittleMaidReengaged (lmreengaged)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
	at net.blacklab.lmr.util.IFF.getFile(IFF.java:259)
	at net.blacklab.lmr.util.IFF.loadIFF(IFF.java:272)
	at net.blacklab.lmr.util.IFF.loadIFFs(IFF.java:238)
	at net.blacklab.lmr.LittleMaidReengaged.postInit(LittleMaidReengaged.java:365)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:616)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:810)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:214)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 36 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_152, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1214212104 bytes (1157 MB) / 1342701568 bytes (1280 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 2 total; -Xms1024M -Xmx2048M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2477 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJ	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJ	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2477-universal.jar) 
	UCHIJ	Forge{12.18.3.2477} [Minecraft Forge] (forge-1.10.2-12.18.3.2477-universal.jar) 
	UCHIJ	OldModelLoader{8.1.4.131} [LMR OldModelLoader] (minecraft.jar) 
	UCHIJ	net.blacklab.lib{6.1.5.8} [EBLib] ([1.9.4-1.10.x]EBLib-6.1.5.8.jar) 
	UCHIE	lmreengaged{8.1.4.131} [LittleMaidReengaged] ([1.9.4-1.10.x]LittleMaidReengaged-8.1.4.131.jar) 
	Loaded coremods (and transformers): 
LMRECoremod ([1.9.4-1.10.x]LittleMaidReengaged-8.1.4.131.jar)
  net.blacklab.lmr.util.coremod.Transformer
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Verclene** [comment]
>Just attempted to launch a server with LMMRE, EBLib, and SpongeForge and this came up:

Fixed. Please update and retry

**Comment by tetsune** [comment]
Success! Maid was spawned via egg! I haven't roamed the world yet to see if there was natural spawns, but that isn't a huge issue.
