### ISSUE TITLE
農家モードによりNullPointerException

### ISSUE THREAD

**Issue by dinhvoluc** [Verclene/LittleMaidReengaged#139]
原因：チェスト(特に１個だけのチェスト）のスタックが空いてない時、メイドは手持ちのアイテムが沢山になって入れようとしたら、エラーが発生しまいました。

この↓はログです：
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Ooh. Shiny.

Time: 5/15/18 11:51 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.blacklab.lmr.entity.ai.EntityAILMFindBlock.func_75251_c(EntityAILMFindBlock.java:162)
	at net.minecraft.entity.ai.EntityAITasks.func_85156_a(SourceFile:68)
	at net.blacklab.lmr.entity.EntityLittleMaid.setMaidModeAITasks(EntityLittleMaid.java:806)
	at net.blacklab.lmr.entity.EntityLittleMaid.setMaidMode(EntityLittleMaid.java:762)
	at net.blacklab.lmr.entity.EntityLittleMaid.setMaidMode(EntityLittleMaid.java:670)
	at net.blacklab.lmr.entity.EntityLittleMaid.setMaidMode(EntityLittleMaid.java:663)
	at net.blacklab.lmr.entity.mode.EntityMode_Farmer.changeMode(EntityMode_Farmer.java:73)
	at net.blacklab.lmr.entity.EntityLittleMaid.setMaidModeAuto(EntityLittleMaid.java:3099)
	at net.blacklab.lmr.entity.EntityLittleMaid.onInventoryChanged(EntityLittleMaid.java:2519)
	at net.blacklab.lmr.entity.EntityLittleMaid.func_70071_h_(EntityLittleMaid.java:2333)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

**Comment by dinhvoluc** [comment]
２，３時間程度にクラシューする。
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Oh - I know what I did wrong!

Time: 5/15/18 3:19 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.blacklab.lmr.entity.ai.EntityAILMFindBlock.func_75251_c(EntityAILMFindBlock.java:162)
	at net.minecraft.entity.ai.EntityAITasks.func_85156_a(SourceFile:68)
	at net.blacklab.lmr.entity.EntityLittleMaid.setMaidModeAITasks(EntityLittleMaid.java:806)
	at net.blacklab.lmr.entity.EntityLittleMaid.setMaidMode(EntityLittleMaid.java:762)
	at net.blacklab.lmr.entity.EntityLittleMaid.setMaidMode(EntityLittleMaid.java:670)
	at net.blacklab.lmr.entity.EntityLittleMaid.setMaidMode(EntityLittleMaid.java:663)
	at net.blacklab.lmr.entity.mode.EntityMode_Farmer.changeMode(EntityMode_Farmer.java:73)
	at net.blacklab.lmr.entity.EntityLittleMaid.setMaidModeAuto(EntityLittleMaid.java:3099)
	at net.blacklab.lmr.entity.EntityLittleMaid.onInventoryChanged(EntityLittleMaid.java:2519)
	at net.blacklab.lmr.entity.EntityLittleMaid.func_70071_h_(EntityLittleMaid.java:2333)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.blacklab.lmr.entity.ai.EntityAILMFindBlock.func_75251_c(EntityAILMFindBlock.java:162)
	at net.minecraft.entity.ai.EntityAITasks.func_85156_a(SourceFile:68)
	at net.blacklab.lmr.entity.EntityLittleMaid.setMaidModeAITasks(EntityLittleMaid.java:806)
	at net.blacklab.lmr.entity.EntityLittleMaid.setMaidMode(EntityLittleMaid.java:762)
	at net.blacklab.lmr.entity.EntityLittleMaid.setMaidMode(EntityLittleMaid.java:670)
	at net.blacklab.lmr.entity.EntityLittleMaid.setMaidMode(EntityLittleMaid.java:663)
	at net.blacklab.lmr.entity.mode.EntityMode_Farmer.changeMode(EntityMode_Farmer.java:73)
	at net.blacklab.lmr.entity.EntityLittleMaid.setMaidModeAuto(EntityLittleMaid.java:3099)
	at net.blacklab.lmr.entity.EntityLittleMaid.onInventoryChanged(EntityLittleMaid.java:2519)
	at net.blacklab.lmr.entity.EntityLittleMaid.func_70071_h_(EntityLittleMaid.java:2333)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)

-- Entity being ticked --
Details:
	Entity Type: lmreengaged:littlemaid (net.blacklab.lmr.entity.EntityLittleMaid)
	Entity ID: 417
	Entity Name: entity.LittleMaid.name
	Entity's Exact location: 4877.33, 56.94, 476.71
	Entity's Block location: World: (4877,56,476), Chunk: (at 13,3,12 in 304,29; contains blocks 4864,0,464 to 4879,255,479), Region: (9,0; contains chunks 288,0 to 319,31, blocks 4608,0,0 to 5119,255,511)
	Entity's Momentum: 0.06, -0.08, 0.01
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: NullPointerException
	All players: 1 total; [EntityPlayerMP['HinotoNashiryoku'/426, l='NullPointerException', x=4871.30, y=57.56, z=470.30]]
	Chunk stats: ServerChunkCache: 578 Drop: 0
	Level seed: 4958355473905625611
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-216,64,200), Chunk: (at 8,4,8 in -14,12; contains blocks -224,0,192 to -209,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1741337 game time, 2389105 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 40692 (now: false), thunder time: 106963 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1275813528 bytes (1216 MB) / 2197815296 bytes (2096 MB) up to 3221225472 bytes (3072 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 96
	FML: MCP 9.42 Powered by Forge 14.23.3.2679 Optifine OptiFine_1.12.2_HD_U_D2 23 mods loaded, 23 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                  | Version      | Source                                             | Signature                                |
	|:--------- |:------------------- |:------------ |:-------------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft           | 1.12.2       | minecraft.jar                                      | None                                     |
	| UCHIJAAAA | mcp                 | 9.42         | minecraft.jar                                      | None                                     |
	| UCHIJAAAA | FML                 | 8.0.99.99    | forge-1.12.2-14.23.3.2679.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge               | 14.23.3.2679 | forge-1.12.2-14.23.3.2679.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | buildcraftlib       | 7.99.16      | buildcraft-7.99.16.jar                             | None                                     |
	| UCHIJAAAA | buildcraftcore      | 7.99.16      | buildcraft-7.99.16.jar                             | None                                     |
	| UCHIJAAAA | buildcraftbuilders  | 7.99.16      | buildcraft-7.99.16.jar                             | None                                     |
	| UCHIJAAAA | buildcraftenergy    | 7.99.16      | buildcraft-7.99.16.jar                             | None                                     |
	| UCHIJAAAA | buildcraftfactory   | 7.99.16      | buildcraft-7.99.16.jar                             | None                                     |
	| UCHIJAAAA | buildcraftrobotics  | 7.99.16      | buildcraft-7.99.16.jar                             | None                                     |
	| UCHIJAAAA | buildcrafttransport | 7.99.16      | buildcraft-7.99.16.jar                             | None                                     |
	| UCHIJAAAA | buildcraftsilicon   | 7.99.16      | buildcraft-7.99.16.jar                             | None                                     |
	| UCHIJAAAA | redstoneflux        | 2.0.1        | RedstoneFlux-1.12-2.0.1.2-universal.jar            | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHIJAAAA | car                 | 1.2.11       | car-1.2.11.jar                                     | None                                     |
	| UCHIJAAAA | net.blacklab.lib    | 6.0.2.5      | EBLib-6.0.2.5.jar                                  | None                                     |
	| UCHIJAAAA | ic2                 | 2.8.73-ex112 | industrialcraft-2-2.8.73-ex112.jar                 | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCHIJAAAA | eu-mj_engine        | 2.2.0        | EU-MJ.Engine-v2.2.jar                              | None                                     |
	| UCHIJAAAA | jei                 | 4.9.1.168    | jei_1.12.2-4.9.1.168.jar                           | None                                     |
	| UCHIJAAAA | lmreengaged         | 8.0.1.66     | LittleMaidReengaged-8.0.1.66-unofficial-1.12.2.jar | None                                     |
	| UCHIJAAAA | reborncore          | 3.8.1.271    | RebornCore-1.12.2-3.8.1.271-universal.jar          | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| UCHIJAAAA | quantumstorage      | 4.5.0        | QuantumStorage-1.12-4.5.0.jar                      | None                                     |
	| UCHIJAAAA | storagenetwork      | 1.12.2-1.2.4 | SimpleStorageNetwork-1.12.2-1.2.4.jar              | None                                     |
	| UCHIJAAAA | xaerominimap        | 1.15         | Xaeros_Minimap_FP1.15_Forge_1.12.jar               | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.8.1.271
		Runtime Debofucsation 1
		RenderEngine: 1
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['HinotoNashiryoku'/426, l='NullPointerException', x=4871.30, y=57.56, z=470.30]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_D2
	OptiFine Build: 20180430-132249
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 391.35
	OpenGlRenderer: GeForce GT 635M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by dinhvoluc** [comment]
チェストが空いてもバグ出る。
チェスト関係のを見直してほしい。
何日間もかかって作ったマップは死んでいます。

**Comment by Verclene** [comment]
Solved!? I am really confused by your closing issues.
I use GitHub to manage tasks like bugfixes, so please, do not do unnecessary action.

**Comment by Verclene** [comment]
That is not my distribution, please report to the author. It is released before this bug being fixed on this repo, so I can't do anything more.
