### ISSUE TITLE
マイクラがクラッシュしました。

### ISSUE THREAD

**Issue by CrafterZ** [Verclene/LittleMaidReengaged#39]
やはり農作業の子が原因でしょうか？フリーにして放置するとクラッシュしました。
クラッシュレポート張っておきます。
---- Minecraft Crash Report ----

WARNING: coremods are present:
  OldModelLoaderCoremod (LittleMaidReengaged-7.1.7.39-1.9.jar)
  FMLPlugin (InventoryTweaks-1.61-dev-44.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 16/05/08 0:48
Description: Ticking entity

java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[down, up, north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:chest, properties=[facing]}
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:192)
    at net.blacklab.lmr.util.helper.CommonHelper.setPathToTile(CommonHelper.java:104)
    at net.blacklab.lmr.entity.mode.EntityMode_Basic.outrangeBlock(EntityMode_Basic.java:311)
    at net.blacklab.lmr.entity.mode.EntityModeBase.outrangeBlock(EntityModeBase.java:200)
    at net.blacklab.lmr.entity.ai.EntityAILMFindBlock.func_75253_b(EntityAILMFindBlock.java:146)
    at net.minecraft.entity.ai.EntityAITasks.func_75773_a(SourceFile:136)
    at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:108)
    at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:760)
    at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2131)
    at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:564)
    at net.minecraft.entity.EntityAgeable.func_70636_d(SourceFile:134)
    at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:41)
    at net.blacklab.lmr.entity.EntityLittleMaid.func_70636_d(EntityLittleMaid.java:2038)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1961)
    at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:296)
    at net.blacklab.lmr.entity.EntityLittleMaid.func_70071_h_(EntityLittleMaid.java:2420)
    at net.minecraft.world.World.func_72866_a(World.java:1934)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:836)
    at net.minecraft.world.World.func_72870_g(World.java:1903)
    at net.minecraft.world.World.func_72939_s(World.java:1737)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:705)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:609)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:148)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:467)
    at java.lang.Thread.run(Unknown Source)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:192)
    at net.blacklab.lmr.util.helper.CommonHelper.setPathToTile(CommonHelper.java:104)
    at net.blacklab.lmr.entity.mode.EntityMode_Basic.outrangeBlock(EntityMode_Basic.java:311)
    at net.blacklab.lmr.entity.mode.EntityModeBase.outrangeBlock(EntityModeBase.java:200)
    at net.blacklab.lmr.entity.ai.EntityAILMFindBlock.func_75253_b(EntityAILMFindBlock.java:146)
    at net.minecraft.entity.ai.EntityAITasks.func_75773_a(SourceFile:136)
    at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:108)
    at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:760)
    at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2131)
    at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:564)
    at net.minecraft.entity.EntityAgeable.func_70636_d(SourceFile:134)
    at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:41)
    at net.blacklab.lmr.entity.EntityLittleMaid.func_70636_d(EntityLittleMaid.java:2038)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1961)
    at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:296)
    at net.blacklab.lmr.entity.EntityLittleMaid.func_70071_h_(EntityLittleMaid.java:2420)
    at net.minecraft.world.World.func_72866_a(World.java:1934)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:836)
    at net.minecraft.world.World.func_72870_g(World.java:1903)

-- Entity being ticked --
Details:
    Entity Type: lmreengaged.LittleMaid (net.blacklab.lmr.entity.EntityLittleMaid)
    Entity ID: 640628
    Entity Name: リトルメイド
    Entity's Exact location: -796.66, 4.00, -275.36
    Entity's Block location: World: (-797,4,-276), Chunk: (at 3,0,12 in -50,-18; contains blocks -800,0,-288 to -785,255,-273), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
    Entity's Momentum: -0.02, -0.08, 0.01
    Entity's Passengers: []
    Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1737)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)

-- Affected level --
Details:
    Level name: シングルテスト
    All players: 1 total; [EntityPlayerMP['***_'/**_*, l='シングルテスト', x=-795.80, y=4.00, z=-275.88]]
    Chunk stats: ServerChunkCache: 625 Drop: 0
    Level seed: 4295281315188581566
    Level generator: ID 01 - flat, ver 0. Features enabled: true
    Level generator options: 
    Level spawn location: World: (-799,4,-275), Chunk: (at 1,0,13 in -50,-18; contains blocks -800,0,-288 to -785,255,-273), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
    Level time: 2339 game time, 2339 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 10474 (now: false), thunder time: 157744 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:705)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:609)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:148)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:467)
    at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
    Minecraft Version: 1.9
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_91, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1755122048 bytes (1673 MB) / 3170893824 bytes (3024 MB) up to 3170893824 bytes (3024 MB)
    JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms3G -Xmx3G -XX:PermSize=256M -XX:MaxPermSize=256M
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP 9.23 Powered by Forge 12.16.1.1887 9 mods loaded, 9 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.9-12.16.1.1887.jar) 
    UCHIJAAAA   Forge{12.16.1.1887} [Minecraft Forge](forge-1.9-12.16.1.1887.jar) 
    UCHIJAAAA   OldModelLoader{7.1.6.35} [LMR OldModelLoader](minecraft.jar) 
    UCHIJAAAA   net.blacklab.lib{5.2.0.3} [EBLib](EBLib-5.2.0.3-1.9.jar) 
    UCHIJAAAA   inventorytweaks{1.61-dev-44-8aeffff} [Inventory Tweaks](InventoryTweaks-1.61-dev-44.jar) 
    UCHIJAAAA   lmreengaged{7.1.6.35} [LittleMaidReengaged](LittleMaidReengaged-7.1.7.39-1.9.jar) 
    UCHIJAAAA   spawnchecker{2.4.0.132} [SpawnChecker](SpawnChecker-2.4.0.132.jar) 
    UCHIJAAAA   spawnchecker.presetmode{2.4.0.132} [SpawnChecker preset mode](SpawnChecker-2.4.0.132.jar) 
    Loaded coremods (and transformers): 
OldModelLoaderCoremod (LittleMaidReengaged-7.1.7.39-1.9.jar)
  net.blacklab.lmr.util.transform.Transformer
FMLPlugin (InventoryTweaks-1.61-dev-44.jar)
  invtweaks.forge.asm.ContainerTransformer
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    Profiler Position: N/A (disabled)
    Player Count: 1 / 8; [EntityPlayerMP['***_'/**_*, l='シングルテスト', x=-795.80, y=4.00, z=-275.88]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Verclene** [comment]
Duplicate #38
