### ISSUE TITLE
INVALID- UNITED ISSUES

### ISSUE THREAD

**Issue by Kohji-Shimazaki** [Verclene/LittleMaidReengaged#72]
#63 からの続き

返信ありがとうございます
使用したバージョンは7.1.8.41ですが、まず1行目「雪の上に居る時Freedomで放っておけば移行するはずですが…」を実際にやってみましたが、雪玉を拾うことはできますが、雪玉を投げられず、ただ歩き回っているだけですので、修正お願いします(8.0.1.67は正常に動作)
続いて、2行目の護衛部隊の追加の件ですが、使用依頼するバージョンは7.1.8.41ではなく、8.0.1.67以降でした。大変に申し訳ございません。メイドモード「護衛騎士」の時かつ剣を持たせている状態で非利き手スロットに盾を持たせると、自動的に「護衛部隊」に変わり、メイドへの受けるダメージが減少あるいは無効化(ガード)をしてくれる仕様です(プレイヤーと同じ効果)。また、メイドモード「護衛部隊」の時に盾を外すと「護衛騎士」に戻る仕様だそうです
次に、8.0.1.67の件について。致命傷後の回復時に突然クラッシュされました

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 16/07/28 21:17
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
    at net.blacklab.lmr.inventory.InventoryLittleMaid.func_70298_a(InventoryLittleMaid.java:547)
    at net.blacklab.lmr.entity.EntityLittleMaid.consumeSugar(EntityLittleMaid.java:3421)
    at net.blacklab.lmr.entity.EntityLittleMaid.func_70636_d(EntityLittleMaid.java:1971)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1976)
    at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:299)
    at net.blacklab.lmr.entity.EntityLittleMaid.func_70071_h_(EntityLittleMaid.java:2261)
    at net.minecraft.world.World.func_72866_a(World.java:1951)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:837)
    at net.minecraft.world.World.func_72870_g(World.java:1920)
    at net.minecraft.world.World.func_72939_s(World.java:1743)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:707)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:611)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:148)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469)
    at java.lang.Thread.run(Unknown Source)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Server thread
Stacktrace:
    at net.blacklab.lmr.inventory.InventoryLittleMaid.func_70298_a(InventoryLittleMaid.java:547)
    at net.blacklab.lmr.entity.EntityLittleMaid.consumeSugar(EntityLittleMaid.java:3421)
    at net.blacklab.lmr.entity.EntityLittleMaid.func_70636_d(EntityLittleMaid.java:1971)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1976)
    at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:299)
    at net.blacklab.lmr.entity.EntityLittleMaid.func_70071_h_(EntityLittleMaid.java:2261)
    at net.minecraft.world.World.func_72866_a(World.java:1951)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:837)
    at net.minecraft.world.World.func_72870_g(World.java:1920)

-- Entity being ticked --
Details:
    Entity Type: lmreengaged.LittleMaid (net.blacklab.lmr.entity.EntityLittleMaid)
    Entity ID: 23
    Entity Name: 【見せられないよ！】
    Entity's Exact location: 513.42, 64.00, -1603.75
    Entity's Block location: World: (513,64,-1604), Chunk: (at 1,4,12 in 32,-101; contains blocks 512,0,-1616 to 527,255,-1601), Region: (1,-4; contains chunks 32,-128 to 63,-97, blocks 512,0,-2048 to 1023,255,-1537)
    Entity's Momentum: 0.00, -0.08, 0.00
    Entity's Passengers: []
    Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1743)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)

-- Affected level --
Details:
    Level name: テストワールド
    All players: 1 total; [EntityPlayerMP['Reimu_38944'/30, l='テストワールド', x=511.71, y=64.00, z=-1601.74]]
    Chunk stats: ServerChunkCache: 420 Drop: 0
    Level seed: -6442014221283275194
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 3;minecraft:bedrock,59_minecraft:stone,3_minecraft:dirt,minecraft:grass,minecraft:snow_layer;12;village,biome_1
    Level spawn location: World: (433,4,-1519), Chunk: (at 1,0,1 in 27,-95; contains blocks 432,0,-1520 to 447,255,-1505), Region: (0,-3; contains chunks 0,-96 to 31,-65, blocks 0,0,-1536 to 511,255,-1025)
    Level time: 166419 game time, 6000 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 60615 (now: false), thunder time: 160349 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:707)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:611)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:148)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469)
    at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
    Minecraft Version: 1.9.4
    Operating System: Windows 10 (x86) version 10.0
    Java Version: 1.8.0_91, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 247813288 bytes (236 MB) / 571494400 bytes (545 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms256M -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.28 Powered by Forge 12.17.0.1976 10 mods loaded, 10 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.9.4-12.17.0.1976.jar) 
    UCHIJAAAA   Forge{12.17.0.1976} [Minecraft Forge](forge-1.9.4-12.17.0.1976.jar) 
    UCHIJAAAA   net.minecraft.scalar.cutall.mod_CutAllSMP{2.5.2} [CutAllSMP]([1.9.4][forge1976]mod_CutAllSMP_v2.5.2.zip) 
    UCHIJAAAA   net.minecraft.scalar.digall.mod_DigAllSMP{2.3.2} [DigAllSMP]([1.9.4][forge1976]mod_DigAllSMP_v2.3.2.zip) 
    UCHIJAAAA   net.minecraft.scalar.mineall.mod_MineAllSMP{2.6.5} [MineAllSMP]([1.9.4][forge1976]mod_MineAllSMP_v2.6.5.zip) 
    UCHIJAAAA   net.minecraft.rosettaenchanttable{0.0.5} [Rosetta Enchant Table]([1.9.4][forge1976]mod_RosettaEnchantTable_v0.0.5.zip) 
    UCHIJAAAA   storagebox{3.0.8} [StorageBox]([1.9.4][forge1976]mod_StorageBox_v3.0.8.zip) 
    UCHIJAAAA   net.blacklab.lib{6.0.2.5} [EBLib](EBLib-6.0.2.5.jar) 
    UCHIJAAAA   lmreengaged{8.0.1.66} [LittleMaidReengaged](LittleMaidReengaged-8.0.1.67.jar) 
    Loaded coremods (and transformers): 
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    Profiler Position: N/A (disabled)
    Player Count: 1 / 8; [EntityPlayerMP['Reimu_38944'/30, l='テストワールド', x=511.71, y=64.00, z=-1601.74]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

だいぶ長い内容になってしまいましたが、どうか修正と追加を宜しくお願いします

**Comment by Verclene** [comment]
「確認された現象」もしくは「要望」ごとに分割して投稿してください.タスク管理のためにGitHubを使用しておりますので.
よろしくお願いします.

**Comment by Kohji-Shimazaki** [comment]
大変ご迷惑をおかけしましたので、#73 #74 #75 に分割しました
