### ISSUE TITLE
メイド仲間後の、ワールドデータクラッシュについて

### ISSUE THREAD

**Issue by noriko-t** [Verclene/LittleMaidReengaged#84]
始めまして、1.9.4環境で以下の問題が発生してしまいました。
質問不慣れで、不手際ありましたら申し訳ありません。
お手数ですがご回答よろしくお願いします。

【概要】
メイドを仲間にしたあとに、マインクラフトを再起動すると、
ワールドデータが起動しなくなる現象が発生しました。

【詳細】
・マインクラフト本体は問題なく起動し、フィールド上にメイドがスポーンします。
・メイドを仲間にした後も、そのままプレイをし続けることが可能です。
・メイドを仲間にした後、ワールドを中断しても、続きからゲームをすることが可能です。
・メイドを仲間にした後、マインクラフトを終了すると、ワールドを読み込むことができません。
　読み込むことができなくなった場合、ランチャー画面に戻ってログが出力される場合と、
　マインクラフトを終了できずに、タスクマネージャから終了する場合があります。
　上記現状場合も、マインクラフト自体は正常に起動し、メイドを仲間にしていないワールドは
　問題なく起動します。

【forge ver】
1.9.4

【MOD ver(ファイル名)】
EBLib-6.0.2.5.jar
LittleMaidReengaged-8.0.1.67.jar

【ログ1】
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 16/10/25 2:32
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/entity/Entity$1
    at net.minecraft.entity.Entity.func_85029_a(Entity.java:2434)
    at net.minecraft.entity.Entity.func_70020_e(Entity.java:1677)
    at net.minecraft.entity.EntityList.func_75615_a(EntityList.java:174)
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_186053_a(AnvilChunkLoader.java:559)
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_186050_a(AnvilChunkLoader.java:486)
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:436)
    at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:77)
    at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:75)
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:123)
    at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:86)
    at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135)
    at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:297)
    at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:173)
    at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:196)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:429)
    at java.lang.Thread.run(Thread.java:745)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.9.4
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 319416816 bytes (304 MB) / 706101248 bytes (673 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
    FML: MCP 9.28 Powered by Forge 12.17.0.1976 Optifine OptiFine_1.9.4_HD_U_B6 9 mods loaded, 9 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAA mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAA FML{8.0.99.99} [Forge Mod Loader](forge-1.9.4-12.17.0.1976.jar) 
    UCHIJAA Forge{12.17.0.1976} [Minecraft Forge](forge-1.9.4-12.17.0.1976.jar) 
    UCHIJAA net.minecraft.scalar.cutall.mod_CutAllSMP{2.5.2} [CutAllSMP]([1.9.4][forge1976]mod_CutAllSMP_v2.5.2.zip) 
    UCHIJAA net.minecraft.scalar.digall.mod_DigAllSMP{2.3.2} [DigAllSMP]([1.9.4][forge1976]mod_DigAllSMP_v2.3.2.zip) 
    UCHIJAA net.minecraft.scalar.mineall.mod_MineAllSMP{2.6.5} [MineAllSMP]([1.9.4][forge1976]mod_MineAllSMP_v2.6.5.zip) 
    UCHIJAA net.blacklab.lib{6.0.2.5} [EBLib](EBLib-6.0.2.5.jar) 
    UCHIJAA journeymap{1.9.4-5.2.4} [JourneyMap](journeymap-1.9.4-5.2.4-unlimited.jar) 
    UCHIJAA lmreengaged{8.0.1.66} [LittleMaidReengaged](LittleMaidReengaged-8.0.1.67.jar) 
    Loaded coremods (and transformers): 
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    Profiler Position: N/A (disabled)
    Player Count: 0 / 8; []
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    OptiFine Version: OptiFine_1.9.4_HD_U_B6
    Render Distance Chunks: 8
    Mipmaps: 0
    Anisotropic Filtering: 1
    Antialiasing: 0
    Multitexture: false
    Shaders: null
    OpenGlVersion: 3.0.0
    OpenGlRenderer: GeForce GTS 250/PCI/SSE2
    OpenGlVendor: NVIDIA Corporation
    CpuCount: 8

【ログ2】
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 16/10/25 3:01
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/entity/Entity$1
    at net.minecraft.entity.Entity.func_85029_a(Entity.java:2434)
    at net.minecraft.entity.Entity.func_70020_e(Entity.java:1677)
    at net.minecraft.entity.EntityList.func_75615_a(EntityList.java:174)
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_186053_a(AnvilChunkLoader.java:559)
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_186050_a(AnvilChunkLoader.java:486)
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:436)
    at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:77)
    at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:75)
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:123)
    at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:86)
    at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135)
    at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:297)
    at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:173)
    at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:196)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:429)
    at java.lang.Thread.run(Thread.java:745)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.9.4
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 362643376 bytes (345 MB) / 833929216 bytes (795 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
    FML: MCP 9.28 Powered by Forge 12.17.0.1976 Optifine OptiFine_1.9.4_HD_U_B6 9 mods loaded, 9 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAAAAA    mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAAAAA    FML{8.0.99.99} [Forge Mod Loader](forge-1.9.4-12.17.0.1976.jar) 
    UCHIJAAAAAAA    Forge{12.17.0.1976} [Minecraft Forge](forge-1.9.4-12.17.0.1976.jar) 
    UCHIJAAAAAAA    net.minecraft.scalar.cutall.mod_CutAllSMP{2.5.2} [CutAllSMP]([1.9.4][forge1976]mod_CutAllSMP_v2.5.2.zip) 
    UCHIJAAAAAAA    net.minecraft.scalar.digall.mod_DigAllSMP{2.3.2} [DigAllSMP]([1.9.4][forge1976]mod_DigAllSMP_v2.3.2.zip) 
    UCHIJAAAAAAA    net.minecraft.scalar.mineall.mod_MineAllSMP{2.6.5} [MineAllSMP]([1.9.4][forge1976]mod_MineAllSMP_v2.6.5.zip) 
    UCHIJAAAAAAA    net.blacklab.lib{6.0.2.5} [EBLib](EBLib-6.0.2.5.jar) 
    UCHIJAAAAAAA    journeymap{1.9.4-5.2.4} [JourneyMap](journeymap-1.9.4-5.2.4-unlimited.jar) 
    UCHIJAAAAAAA    lmreengaged{8.0.1.66} [LittleMaidReengaged](LittleMaidReengaged-8.0.1.67.jar) 
    Loaded coremods (and transformers): 
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    Profiler Position: N/A (disabled)
    Player Count: 0 / 8; []
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    OptiFine Version: OptiFine_1.9.4_HD_U_B6
    Render Distance Chunks: 8
    Mipmaps: 0
    Anisotropic Filtering: 1
    Antialiasing: 0
    Multitexture: false
    Shaders: null
    OpenGlVersion: 3.0.0
    OpenGlRenderer: GeForce GTS 250/PCI/SSE2
    OpenGlVendor: NVIDIA Corporation
    CpuCount: 8

**Comment by Verclene** [comment]
スーパーフラット等特定のワールドタイプにおいて類似現象が発生することを確認していますが,はっきり言って全く原因に心当たりが無く修正不可の状況です.

**Comment by noriko-t** [comment]
了解しました。
ご回答ありがとうございました。
