### ISSUE TITLE
雇用後のワールドを読み込みません

### ISSUE THREAD

**Issue by makooh** [Verclene/LittleMaidReengaged#87]
メイドさんの雇用後、ワールドを読み込まなくなります。
強制終了し、Game Outputを確認すると、
以下のログがループで表示され続けています。

--------------------------------------------------
[06:56:09] [Server thread/INFO] [STDERR]: [net.blacklab.lmr.entity.EntityLittleMaid:<init>:342]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[06:56:09] [Server thread/INFO] [STDERR]: [net.blacklab.lmr.entity.EntityLittleMaid:<init>:342]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[06:56:09] [Server thread/INFO] [STDERR]: [net.blacklab.lmr.entity.EntityLittleMaid:<init>:342]: 	at net.minecraft.entity.EntityList.func_75615_a(EntityList.java:162)
[06:56:09] [Server thread/INFO] [STDERR]: [net.blacklab.lmr.entity.EntityLittleMaid:<init>:342]: 	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_186053_a(AnvilChunkLoader.java:559)
[06:56:09] [Server thread/INFO] [STDERR]: [net.blacklab.lmr.entity.EntityLittleMaid:<init>:342]: 	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_186050_a(AnvilChunkLoader.java:486)
[06:56:09] [Server thread/INFO] [STDERR]: [net.blacklab.lmr.entity.EntityLittleMaid:<init>:342]: 	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:436)
[06:56:09] [Server thread/INFO] [STDERR]: [net.blacklab.lmr.entity.EntityLittleMaid:<init>:342]: 	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:77)
[06:56:09] [Server thread/INFO] [STDERR]: [net.blacklab.lmr.entity.EntityLittleMaid:<init>:342]: 	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:75)
[06:56:09] [Server thread/INFO] [STDERR]: [net.blacklab.lmr.entity.EntityLittleMaid:<init>:342]: 	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:123)
[06:56:09] [Server thread/INFO] [STDERR]: [net.blacklab.lmr.entity.EntityLittleMaid:<init>:342]: 	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:86)
[06:56:09] [Server thread/INFO] [STDERR]: [net.blacklab.lmr.entity.EntityLittleMaid:<init>:342]: 	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135)
[06:56:09] [Server thread/INFO] [STDERR]: [net.blacklab.lmr.entity.EntityLittleMaid:<init>:342]: 	at net.minecraft.world.World.func_72964_e(World.java:301)
[06:56:09] [Server thread/INFO] [STDERR]: [net.blacklab.lmr.entity.EntityLittleMaid:<init>:342]: 	at net.minecraft.world.World.func_175726_f(World.java:296)
[06:56:09] [Server thread/INFO] [STDERR]: [net.blacklab.lmr.entity.EntityLittleMaid:<init>:342]: 	at net.minecraft.world.World.func_175672_r(World.java:1605)
[06:56:09] [Server thread/INFO] [STDERR]: [net.blacklab.lmr.entity.EntityLittleMaid:<init>:342]: 	at net.minecraft.world.WorldProvider.getRandomizedSpawnPoint(WorldProvider.java:335)
[06:56:09] [Server thread/INFO] [STDERR]: [net.blacklab.lmr.entity.EntityLittleMaid:<init>:342]: 	at net.minecraft.entity.player.EntityPlayerMP.<init>(EntityPlayerMP.java:145)
[06:56:09] [Server thread/INFO] [STDERR]: [net.blacklab.lmr.entity.EntityLittleMaid:<init>:342]: 	at net.minecraftforge.common.util.FakePlayer.<init>(FakePlayer.java:23)
[06:56:09] [Server thread/INFO] [STDERR]: [net.blacklab.lmr.entity.EntityLittleMaid:<init>:342]: 	at net.blacklab.lmr.entity.EntityLittleMaidAvatarMP.<init>(EntityLittleMaidAvatarMP.java:49)
[06:56:09] [Server thread/INFO] [STDERR]: [net.blacklab.lmr.entity.EntityLittleMaid:<init>:342]: 	at net.blacklab.lmr.entity.EntityLittleMaidAvatarMP.<init>(EntityLittleMaidAvatarMP.java:54)
[06:56:09] [Server thread/INFO] [STDERR]: [net.blacklab.lmr.entity.EntityLittleMaid:<init>:342]: 	at net.blacklab.lmr.entity.EntityLittleMaid.<init>(EntityLittleMaid.java:340)
[06:56:09] [Server thread/INFO] [STDERR]: [net.blacklab.lmr.entity.EntityLittleMaid:<init>:342]: 	at sun.reflect.GeneratedConstructorAccessor68.newInstance(Unknown Source)

--------------------------------------------------
MOD構成は
forge1.9.4 - 12.17.0.1976
OptiFine_1.9.4_HD_U_B6.jar
EBLib-6.0.2.5.jar
LittleMaidReengaged-8.0.1.67.jar

lmre-voms-src-190.zip
littleMaidMob-Elsa5-190.zip
littleMaidMob-Chloe2-190.zip
littleMaidMob-Beverly7-190.zip
singingMaid-20130816.zip

%5B1.9.4%5D%5Bforge1976%5Dmod_MineAllSMP_v2.6.5.zip
%5B1.9.4%5D%5Bforge1976%5Dmod_CutAllSMP_v2.5.2.zip
%5B1.9.4%5D%5Bforge1976%5Dmod_DigAllSMP_v2.3.2.zip

SEED値は、4494144197845194987　です。

littleMaidMobNXでも同じ症状が起き、
一旦、MODsから削除し、雇用メイドを削除するとワールドを読み込めます。
MODsに入れ直した時点では、まだ読み込めますが、
再雇用すると、また読み込めなくなっていました。
SEED値は同じです。

メイドさんがを生かしたまま、プレイを続行する方法はあるでしょうか？

**Comment by Verclene** [comment]
元のログデータをpastebinとかでください。
ただこの手の不具合はずっと頭を痛めておりまして、修正の目処が立っていません。
手の出せない所でエラーを起こしているため原因すらふかめて掴めていない状況です。

**Comment by makooh** [comment]
pastebinを試してみたところ、容量制限 512KB超えと出てしまったので、
zipで宅ファイル便に上げてみましたが、これでもよいでしょうか？
https://free.filesend.to/filedn_infoindex?rp=48ed9650b9a6501f347a01c5eab48c3o

**Comment by Verclene** [comment]
拝見しましたがまったく手が出せないようです.
なぜカレンダー周りのStackOverFlowが出るのかなぜEntity$1が見つからないと怒られるのか,正直意味不明です.
前から処理方法が気になっている重複削除処理かASMが引っかかってるのかなあとかくらいしか思いつかないので,この件に関しては一旦closeさせていただきます…

**Comment by makooh** [comment]
ご確認ありがとうございます。
いただいたコメントを参考に、また同一SEEDでテストしていたところ

雇用してセーブ終了 =　正常に読み込み
料理人にして、かまど使用中にセーブ終了　=　同じエラーログ、再開不可
料理人にして、かまど使用後にセーブ終了　=　同じエラーログ、再開不可
料理人にして、かまど使用後に、農家の娘に変更してセーブ終了　=　正常に読み込み

つまり終了時に「料理人モード」になっていると発生しているようです。（あくまで私の環境下ですが）
実体がエンティティに戻っていない的な？

ちなみに、NXのほうでも同じテストをしてみましたが、
こちらはかまど使用直後でも正常に再開できていますので、違うようです。
こまめにバックアップしながらプレイしてみます。

**Comment by haoling** [comment]
こちらの問題についてですが、わたしの環境で再現しましたので検証を行いました。
わたしの環境の場合は、スポーンエリア付近にメイドがいるときに、ワールドの読み込み時に大量にエラーが出て、時間がかかるもののワールドは読み込めますが、メイドはすべて居ない、という現象でした。

スタックトレースから推測するに、以下の流れでスタックオーバーフローを起こしているようでした。
・スポーン地点のチャンクを読み込む。
・読み込んだチャンクにいるEntityを生成・初期化する。
・生成されるEntityの中にメイドがいるので、EntityLittleMaidのコンストラクタを呼ぶ。
・EntityLittleMaidのコンストラクタでEntityLittleMaidAvatarMPのインスタンスを生成する。
・EntityLittleMaidAvatarMPの親クラスであるFakePlayerのコンストラクタが呼ばれる。
・FakePlayerのコンストラクタの内部でgetRandomRespawnPointメソッドが呼ばれる。
・全ユーザーのリスポーン地点は同一のため、getRandomizedSpawnPointメソッドによってスポーン地点のチャンクの読み込みが行われる。
・以下、一番上に戻る。

上記のような理由のため、EntityTameableのコンストラクタ内部でFakePlayerのインスタンスを生成してはならない、またはFakePlayerFactoryを使用しなければならないのかと思われますが、現状のEntityLittleMaidAvatarMPクラスを改変するのは **とても** 大変そうだったので、 `maidAvater = new EntityLittleMaidAvatarMP()` の呼び出しを遅らせることにしました。

というわけでプルリクを作りましたので、ご確認いただけますと幸いです。
現状、ほとんど検証出来ておりませんので、人柱版などでまずは出していただき、みなさまのご協力の下で不具合の修正が出来ればと思います。
どうぞよろしくお願い致します。


（わたくし、ひとさまのリポジトリにプルリク投げつけるのは生まれて初めてです。なにか間違ってましたらごめんなさい。）

**Comment by haoling** [comment]
追伸：ビルド環境をgradleにしていただいたおかげで、デバッグがとてもはかどりました。ありがとうございます。

**Comment by Verclene** [comment]
@haoling ありがとうございます.私事情もありまともに検証できていなかったのでとても助かりました.

が,宛先がfork先のようで,こちらからはソースを流用はできてもそのPR自体はどうにもできないのです…(こちらのリポジトリからforkされないと,このリポジトリに対するPRとして処理されないです)
ともかくにも,来週あたりようやくまとまった時間が取れそうなので,頂いたコードで対応します.

**Comment by haoling** [comment]
おぉ？おぉ、なるほど、眠気ギリギリで作業してたので、いろいろ間違ってしまいました。。。

とりあえず、まだいろいろ未検証なのでマージしていただける段階ではないと思いますので、人柱版のバイナリへのリンクだけ残して、プルリク自体はいったんクローズしてしまいます。
近いうちにgradle化のほうも混ぜて（勝手にぱくって）全体的なプルリクを作らせていただきます。
お騒がせしました。

そうか、1.9.4版と1.11.2版もビルドせにゃ・・・

**Comment by haoling** [comment]
申し訳ありません、結論から言ってダメでした。自分のワールドを再起動したところ、現象が再発しました。

getRandomRespawnPointの内部でチャンクロードが発生し、その結果としてEntityの読み込みがループする原因ですが、スポーンポイントをランダムにする処理の内部で、固体ブロックかどうかの判定が入っているため、チャンクを読み込もうとしています。
gameruleの `spawnRadius` を0にするとチャンクの読み込みそのものが行われないようになるため、一時的にgameruleを書き換える処理に変更してみました。

人柱版バイナリはこちらです。
https://drive.fei-yen.jp/index.php/s/J7AHin7biek9CqG
（5/11更新： #47 を手mergeしました）

コミットはこちらです。
https://github.com/haoling/LittleMaidReengaged/commit/1c9b503db23a581c27f3bcd00a771a5dcdfad401

これで再度検証してみたいと思います。

**Comment by Shionsan** [comment]
Off topic, but I'd like to thank haoling for 1.10.2 mod build. M3 models still not working, but at least I can play with maids again. Thank you!

**Comment by haoling** [comment]
@Verclene プルリクを作り直しました。まだまだテスト不足ですが、置いておきます。
